### PR TITLE
Made plugin IDEA 15 compatible (still works in IDEA 14.1.X, other ver…

### PR DESCRIPTION
**Pull request by Arcnor**
…sions not tested).

One thing that I'm getting in IDEA 15 is that maps (`[:]`) are being marked as incorrect, but tried with IDEA 14 and it seems to work... In any case, that's better than having the plugin fail to load completely.

### CODE REVIEW

**Comment by matiwinnetou** [comment]
can this be merged and released please.

**Comment by matiwinnetou** [comment]
@Arcnor do you have a jar somewhere for install from jar option?

**Comment by evenaglia** [comment]
Just merged it in, but I still need to get a IJ15 dev environment running to test everything. Hopefully I can also fix the ConcurrentModificationException that's been nagging me forever.

https://github.com/evenaglia/Non-Dairy-Soy-Plugin/issues/12

**Comment by matiwinnetou** [comment]
Can you build this and release please? If there was a gradle, maven or whatever build I would do this myself but I don't even know how to.

**Comment by kayneb** [comment]
Likewise ^

**Pull request merged**
